name: elcm

model_type: segmented_discretechoice

segmentation_col: sector

choosers_fit_filters: building_id != -1

choosers_predict_filters: null

alts_fit_filters: null

alts_predict_filters:
- job_spaces > 0

interaction_predict_filters: null

choice_column: null

sample_size: 50

estimation_sample_size: 200

prediction_sample_size: null

default_config:
    model_expression: np.log1p(non_residential_rent) + office_1500 + industrial_1500
        + retail_1500 + jobs_45 + residential_units_1500 + residential_units_45 +
        ave_income_1500 + juris_ave_income + embarcadero + stanford

choice_mode: aggregate

remove_alts: true

probability_mode: single_chooser
